import {
  Loader2,
  LayoutDashboard,
  Package,
  ShoppingCart,
  BarChart3,
  Settings,
  User,
  LogOut,
  Menu,
  X,
  Search,
  Plus,
  Edit,
  Trash2,
  Download,
  Upload,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ArrowUp,
  ArrowDown,
  Check,
  AlertTriangle,
  Calendar,
  Filter,
  RefreshCw,
  Save,
  Lock,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  dashboard: LayoutDashboard,
  inventory: Package,
  orders: ShoppingCart,
  reports: BarChart3,
  settings: Settings,
  user: User,
  logout: LogOut,
  menu: Menu,
  close: X,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  download: Download,
  upload: Upload,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: Check,
  alert: AlertTriangle,
  calendar: Calendar,
  filter: Filter,
  refresh: RefreshCw,
  save: Save,
  login: Lock,
  lock: Lock,
};